<table class="table table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>nom</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->plantes as $plante) : ?>
            <tr>
                <td><?php echo $plante->getId() ?></td>
                <td><?php echo $plante->getNom() ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>